### ISSUE TITLE
чё с импортами?

### ISSUE THREAD

**Issue by IIDarkNessYT** [ret7020/vk-Raid-PyPro#1]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import tkinter, time
ModuleNotFoundError: No module named 'tkinter'

**Comment by ret7020** [comment]
Запускаете на VPS?

**Comment by IIDarkNessYT** [comment]
на своём пк

**Comment by ret7020** [comment]
Если из под Linux на Debian based(например Ubuntu), то должно помочь:
 `sudo apt-get install python3-tk`

**Comment by IIDarkNessYT** [comment]
Ок, попробую
